// ============================================================================
// Object3D_WaterColumn.PS.hlsl
// ----------------------------------------------------------------------------
// Water column pixel shader for heavy splash effect.
// Features:
//   - Upward scrolling noise for rushing water effect
//   - Alpha fade at top and bottom of cylinder
//   - Fresnel reflection and environment mapping
// ============================================================================

#include "Object3d.hlsli"

// ---------- Constant Buffers ----------

struct Material
{
    float4 color;
    int lightingMode;
    float shininess;
    float environmentCoefficient;
    float padding;
    float4x4 uvTransform;
};
ConstantBuffer<Material> gMaterial : register(b0);

struct DirectionalLight
{
    float4 color;
    float3 direction;
    float intensity;
    float3 ambientColor;    // 環境光の色
    float ambientIntensity; // 環境光の強さ（0 で環境光なし）
};
ConstantBuffer<DirectionalLight> gDirectionalLight : register(b1);

struct Camera
{
    float3 worldPosition;
};
ConstantBuffer<Camera> gCamera : register(b2);

struct PointLight
{
    float4 color;
    float3 position;
    float intensity;
    float radius;
    float decay;
    float2 padding;
};
static const uint MAX_POINT_LIGHTS = 256;
cbuffer PointLightsCB : register(b3)
{
    uint pointCount;
    float3 _padPoint;
    PointLight pointLights[MAX_POINT_LIGHTS];
};

struct SpotLight
{
    float4 color;
    float3 position;
    float intensity;
    float3 direction;
    float distance;
    float decay;
    float cosAngle;
    float2 padding;
};
static const uint MAX_SPOT_LIGHTS = 256;
cbuffer SpotLightsCB : register(b4)
{
    uint spotCount;
    float3 _padSpot;
    SpotLight spotLights[MAX_SPOT_LIGHTS];
};

struct AreaLight
{
    float4 color;
    float3 position;
    float intensity;
    float3 right;
    float halfWidth;
    float3 up;
    float halfHeight;
    float range;
    float decay;
    uint twoSided;
    uint pad;
};
static const uint MAX_AREA_LIGHTS = 256;
cbuffer AreaLightsCB : register(b5)
{
    uint areaCount;
    float3 _padArea;
    AreaLight areaLights[MAX_AREA_LIGHTS];
};

Texture2D<float4> gTexture : register(t0);
TextureCube<float4> gEnvironmentTexture : register(t1);
SamplerState gSampler : register(s0);

struct PixelShaderOutput
{
    float4 color : SV_TARGET0;
};

// ==========================================================================
// Utility functions
// ==========================================================================

float hash31(float3 p)
{
    p = frac(p * 0.1031);
    p += dot(p, p.yzx + 33.33);
    return frac((p.x + p.y) * p.z);
}

float noise3D(float3 p)
{
    float3 i = floor(p);
    float3 f = frac(p);
    f = f * f * (3.0 - 2.0 * f);

    float n000 = hash31(i + float3(0, 0, 0));
    float n100 = hash31(i + float3(1, 0, 0));
    float n010 = hash31(i + float3(0, 1, 0));
    float n110 = hash31(i + float3(1, 1, 0));
    float n001 = hash31(i + float3(0, 0, 1));
    float n101 = hash31(i + float3(1, 0, 1));
    float n011 = hash31(i + float3(0, 1, 1));
    float n111 = hash31(i + float3(1, 1, 1));

    float nx00 = lerp(n000, n100, f.x);
    float nx10 = lerp(n010, n110, f.x);
    float nx01 = lerp(n001, n101, f.x);
    float nx11 = lerp(n011, n111, f.x);

    float nxy0 = lerp(nx00, nx10, f.y);
    float nxy1 = lerp(nx01, nx11, f.y);

    return lerp(nxy0, nxy1, f.z);
}

float fbm3(float3 p)
{
    float val = 0.0;
    float amp = 0.5;
    float freq = 1.0;
    for (int i = 0; i < 3; ++i)
    {
        val += amp * noise3D(p * freq);
        freq *= 2.17;
        amp *= 0.5;
    }
    return val;
}

float FresnelSchlick(float cosTheta, float F0)
{
    float x = 1.0 - saturate(cosTheta);
    float x2 = x * x;
    float x5 = x2 * x2 * x;
    return F0 + (1.0 - F0) * x5;
}

// ==========================================================================
// Main
// ==========================================================================

PixelShaderOutput main(VertexShaderOutput input)
{
    PixelShaderOutput output;

    // We use uvTransform._42 (row 3, col 1) as a time variable passed from C++
    float timeOffset = gMaterial.uvTransform[3][1];

    // Texture sample with scrolling UV
    float4 uv = mul(float4(input.texcoord, 0.0, 1.0), gMaterial.uvTransform);
    float4 tex = gTexture.Sample(gSampler, uv.xy);
    float4 base = gMaterial.color * tex * input.instColor;

    // Use texcoord.y to fade out the top and bottom of the cylinder
    float v = input.texcoord.y;
    // Cylinder generated by MeshGenerator usually has v=0 at top, v=1 at bottom.
    float heightFade = smoothstep(0.0, 0.15, v) * smoothstep(1.0, 0.85, v);

    if (base.a <= 0.001 || heightFade <= 0.001)
        discard;

    // Water color tint
    float3 waterDeep   = float3(0.05, 0.35, 0.65);
    float3 waterBright = float3(0.45, 0.85, 1.0);
    float3 waterFoam   = float3(0.8, 0.95, 1.0);

    // Scroll world position downward in noise space, so water looks like it's rushing UP
    float3 wp = input.worldPosition + float3(0.0, timeOffset * 15.0, 0.0);

    // Stretch noise vertically to look like rushing streaks
    float3 noisePos = float3(wp.x * 5.0, wp.y * 1.5, wp.z * 5.0);
    float noiseVal = fbm3(noisePos);

    float3 waterColor = lerp(waterDeep, waterBright, noiseVal);

    float foamMask = smoothstep(0.5, 0.75, noiseVal);
    waterColor = lerp(waterColor, waterFoam, foamMask * 0.6);

    waterColor *= base.rgb * 2.0;

    // Vectors
    float3 N = normalize(input.normal);
    float3 V = normalize(gCamera.worldPosition - input.worldPosition);

    // Perturb normal for rushing water
    float eps = 0.05;
    float nx = fbm3(noisePos + float3(eps, 0, 0)) - fbm3(noisePos - float3(eps, 0, 0));
    float ny = fbm3(noisePos + float3(0, eps, 0)) - fbm3(noisePos - float3(0, eps, 0));
    float nz = fbm3(noisePos + float3(0, 0, eps)) - fbm3(noisePos - float3(0, 0, eps));
    float3 noiseNormal = normalize(float3(nx, ny, nz));

    N = normalize(N + noiseNormal * 0.4);

    if (dot(N, V) < 0.0)
        N = -N;

    float NdotV = saturate(dot(N, V));

    // Fresnel
    float F0 = 0.02;
    float fresnel = FresnelSchlick(NdotV, F0);
    float shininess = max(gMaterial.shininess, 300.0);

    // Lighting
    float3 diffuseSum = 0.0;
    float3 specularSum = 0.0;

    // Directional light
    {
        float3 L = normalize(-gDirectionalLight.direction);
        float NdotL = saturate(dot(N, L));
        float diffuseTerm = NdotL * NdotL;

        float3 lightCol = gDirectionalLight.color.rgb * gDirectionalLight.intensity;
        diffuseSum += waterColor * lightCol * diffuseTerm;

        if (NdotL > 0.0)
        {
            float3 H = normalize(L + V);
            float specPow = pow(saturate(dot(N, H)), shininess);
            specularSum += lightCol * specPow;
        }
    }

    // Point lights
    [loop]
    for (uint i = 0; i < MAX_POINT_LIGHTS; ++i)
    {
        if (i >= pointCount) break;
        PointLight pl = pointLights[i];
        if (pl.intensity <= 0.0 || pl.radius <= 0.0) continue;

        float3 toL = pl.position - input.worldPosition;
        float dist = length(toL);
        if (dist >= pl.radius || dist <= 1e-5) continue;

        float3 L = toL / dist;
        float t = saturate(1.0 - dist / pl.radius);
        float atten = pow(t, max(pl.decay, 0.0001));

        float NdotL = saturate(dot(N, L));
        float diffuseTerm = NdotL * NdotL;

        float3 lightCol = pl.color.rgb * pl.intensity * atten;
        diffuseSum += waterColor * lightCol * diffuseTerm;

        if (NdotL > 0.0)
        {
            float3 H = normalize(L + V);
            float specPow = pow(saturate(dot(N, H)), shininess);
            specularSum += lightCol * specPow;
        }
    }

    // Environment reflection
    float3 reflectedVec = reflect(-V, N);
    float4 envColor = gEnvironmentTexture.Sample(gSampler, reflectedVec);

    // Subsurface scattering
    float3 L_dir = normalize(-gDirectionalLight.direction);
    float sss = saturate(dot(V, -L_dir)) * 0.4;
    float3 subsurface = waterBright * gDirectionalLight.color.rgb * gDirectionalLight.intensity * sss;

    // Composite
    float3 reflection = specularSum * (0.5 + 2.0 * fresnel);
    reflection += envColor.rgb * fresnel * 0.8;

    // Opacity fades at the edges using heightFade
    float opacity = saturate(base.a * heightFade * 0.9 + fresnel * 0.4 * heightFade);

    float innerGlow = smoothstep(0.0, 0.5, NdotV) * 0.2;
    float3 glowColor = waterBright * innerGlow;

    float3 finalColor = diffuseSum + subsurface + glowColor;

    // Add extra brightness where foam is strong
    finalColor += waterFoam * foamMask * 0.5;

    output.color.rgb = saturate(finalColor * opacity + reflection);
    output.color.a = opacity;

    return output;
}
